# Generated by Django 3.2.9 on 2021-12-01 18:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('botlogic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='server',
            name='members_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='server',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
